services:
  postgres:
    image: postgres:16
    container_name: fiscal-documents-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10


  rabbitmq:
    image: rabbitmq:4.3.5-management
    container_name: fiscal-documents-rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  worker:
    build:
      context: .
      dockerfile: FiscalDocuments.Worker/Dockerfile

    container_name: fiscal-documents-worker

    environment:
      ConnectionStrings__DefaultConnection: >
        Host=postgres;
        Port=5432;
        Database=${POSTGRES_DB};
        Username=${POSTGRES_USER};
        Password=${POSTGRES_PASSWORD}

      RabbitMq__Host: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__User: ${RABBITMQ_USER}
      RabbitMq__Password: ${RABBITMQ_PASSWORD}

    depends_on:
      postgres:
        condition: service_healthy

      rabbitmq:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: FiscalDocuments.Api/Dockerfile

    container_name: fiscal-documents-api

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080


      ConnectionStrings__DefaultConnection: >
        Host=postgres;
        Port=5432;
        Database=${POSTGRES_DB};
        Username=${POSTGRES_USER};
        Password=${POSTGRES_PASSWORD}
      
      RabbitMq__Host: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__User: ${RABBITMQ_USER}
      RabbitMq__Password: ${RABBITMQ_PASSWORD}

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  rabbitmq_data: