<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-FiscalDocuments.Worker-9c4d6a67-6dcb-42fc-aaa5-0a3ef65fcf62</UserSecretsId>
    
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.1" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FiscalDocuments.Api\FiscalDocuments.Api.csproj" />
  </ItemGroup>
</Project>
